---
ec2_name_prefix: TRAINING
ec2_region: us-east-1
ec2_wait: true
ec2_az: "{{ec2_region}}a"
ec2_subnet: "172.16.0.0/16"
ec2_subnet2: "172.17.0.0/16"
ec2_network_vpc2: "172.18.0.0/16"
ssh_port: 22
create_cluster: false

control_type: "rhel8-tower"
rhel: "rhel8"
# additional info needed by AWS ec2 modules
ec2_info:
  windows_ws:
    owners: 679593333241
    filter: 'Windows_Server-2016-English-Full-Base*'
    size: m5.xlarge
    ami: "{{ windows_ws_ami| default(omit) }}"
    username: Administrator
  # Look for owner 309956199498 to find official Red Hat AMIs
  rhel8-tower:
    owners: 309956199498
    size: t2.medium
    os_type: linux
    disk_space: 20
    architecture: x86_64
    filter: 'RHEL-8*HVM-*Hourly*'
    username: ec2-user
  rhel8:
    owners: 309956199498
    size: t3.micro
    os_type: linux
    disk_space: 10
    architecture: x86_64
    filter: 'RHEL-8*HVM-*Hourly*'
    username: ec2-user
  hana:
    owners: 309956199498
    size: m5.8xlarge
    os_type: linux
    architecture: x86_64
    #filter: 'RHEL-8*HVM-*Hourly*'
    filter: 'RHEL-8.1.0_HVM*x86_64*Access*'
    username: ec2-user
    volumes:
      - device_name: /dev/sda1
        volume_type: gp3
        volume_size: 45
        delete_on_termination: true
      - device_name: /dev/xvdb
        volume_type: gp3
        volume_size: 528
        delete_on_termination: true
  s4app:
    owners: 309956199498
    size: m5.4xlarge
    os_type: linux
    architecture: x86_64
    #filter: 'RHEL-8*HVM-*Hourly*'
    filter: 'RHEL-8.1.0_HVM*x86_64*Access*'
    username: ec2-user
    volumes:
      - device_name: /dev/sda1
        volume_type: gp3
        volume_size: 45
        delete_on_termination: true
      - device_name: /dev/xvdb
        volume_type: gp3
        volume_size: 400
        delete_on_termination: true
  rhel7:
    owners: 309956199498
    size: t3.micro
    os_type: linux
    disk_space: 10
    architecture: x86_64
    filter: 'RHEL-7.7_HVM_GA-20190723-x86_64-1-Access2-GP2'
    username: ec2-user
    python_interpreter: '/usr/bin/python'
  attendance_host:
    owners: 309956199498
    size: t3.micro
    os_type: linux
    disk_space: 10
    architecture: x86_64
    filter: 'RHEL-8*HVM-*Hourly*'
    username: ec2-user
debug_teardown: false
