---
- name: find ami for rhel node
  ec2_ami_info:
    region: "{{ ec2_region }}"
    owners: "{{ ec2_info[rhel].owners }}"
    filters:
      name: "{{ ec2_info[rhel].filter }}"
      architecture: "{{ ec2_info[rhel].architecture }}"
  register: amis

- name: save ami for node
  set_fact:
    node_ami: >
      {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}

- name: find ami for hana node
  ec2_ami_info:
    region: "{{ ec2_region }}"
    filters:
      name: "{{ ec2_info['hana']['filter'] }}"
      architecture: "{{ ec2_info[rhel].architecture }}"
  register: hana_amis

- name: save ami for hana
  set_fact:
    hana_ami: >
      {{ hana_amis['images'] | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}

- name: find ami for s4app node
  ec2_ami_info:
    region: "{{ ec2_region }}"
    filters:
      name: "{{ ec2_info['s4app']['filter'] }}"
      architecture: "{{ ec2_info[rhel].architecture }}"
  register: s4app_amis

- name: save ami for s4app
  set_fact:
    s4app_ami: >
      {{ s4app_amis['images'] | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}

- name: find ami for windows node
  ec2_ami_info:
    region: "{{ ec2_region }}"
    filters:
      name: "{{ ec2_info['windows_ws']['filter'] }}"
  register: windows_ws_amis

- name: save ami for windows
  set_fact:
    windows_ws_ami: >
      {{ windows_ws_amis['images'] | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}