---

- name: add hosts to inventory
  include_tasks: 'inventory/addhost_{{ workshop_type }}.yml'

- block:
    - name: unregister redhat-insights
      command: redhat-access-insights --unregister
      failed_when: false
      ignore_unreachable: yes
      become: yes
      delegate_to: "{{ hostvars[item].ansible_host }}"
      loop: "{{ groups.sap_nodes }}"
      changed_when: no

    - name: unregister rhn if available
      command: subscription-manager unregister
      failed_when: false
      ignore_unreachable: yes
      become: yes
      delegate_to: "{{ hostvars[item].ansible_host }}"
      loop: "{{ groups.sap_nodes }}"
      changed_when: no

    - name: clean rhn registration
      redhat_subscription:
        state: absent
      failed_when: false
      ignore_unreachable: yes
      become: yes
      delegate_to: "{{ hostvars[item].ansible_host }}"
      loop: "{{ groups.sap_nodes }}"
  when: groups.sap_nodes is defined
