---
- name: Perform Checks to make sure this Playbook will complete successfully
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  tasks:
    - name: run pre-check role to make sure workshop will complete provisioning
      include_role:
        name: workshop_check_setup

    - name: run AWS check setup if using AWS
      include_role:
        name: aws_check_setup

- name: Create lab instances in AWS
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  roles:
    - manage_ec2_instances

- name: wait for all nodes to have SSH reachability
  hosts: "managed_nodes:control_nodes:attendance"
  become: true
  gather_facts: false
  roles:
    - connectivity_test

- name: Configure nginx on attendance host
  hosts: attendance
  become: true
  gather_facts: true
  tasks:
    - block:
        - include_role:
            name: workshop_attendance_nginx
        - include_role:
            name: workshop_attendance
      when: attendance|bool